
          
name: Node.js CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    
    # Build    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm -g install @vue/cli
    - run: npm run build --if-present
    
    - name: Azure Storage Action
      uses: lauchacarro/Azure-Storage-Action@v1.1
      with:
        connection-string: {AZURESTORAGECONNECTIONSTRING}
        folder: "./docs"
        blob-container-name: "pchealth/app"

    
