
          
name: Node.js CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    
    # Build    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm -g install @vue/cli
    - run: npm run build --if-present
    
    - name: azure-blob-copy-action
  # You may pin to the exact commit or the version.
  # uses: ulaval/azure-blob-copy-action@a5589c66042be9a15da7cc2a28e63adc3a42af3a
      uses: ulaval/azure-blob-copy-action@v1
      with:
          # Either upload or download
         action: upload
         # Azure Blob Storage connection string
         connection_string: ${{secrets.AZURESTORAGECONNECTIONSTRING}}
         # Azure Blob Storage container name
         container_name: pchealth
         # Directory in Azure to copy from or to
         blob_directory: app
         # Local directory to copy from or to; this can either be an absolute path or a relative path
         local_directory: docs
